<?php
/**
 * This is a modified version of the core catalog/product/view/media.phtml
 * Any changes you had made to the previous media file must be changed here as well for changes to take effect.
 * System > Configuration > Video Gallery > Display Style > Style 02
 */
?>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<div id="vg-style-02">

	<?php echo $this->getImagesMedia(); ?>
	<?php if (count($this->getVideoGallery()) > 0): ?>
	
	<div class="more-views">
	    <h2><?php echo $this->__('Videos') ?></h2>
		<?php if (count($this->getVideoGallery()) > 0): ?>
		<?php $isMobile = $this->isMobile(); ?>
	    <ul class="video-gallery-links">
	    <?php foreach ($this->getVideoGallery() as $_video): ?>
	        <li>
	        	<?php if ($isMobile): ?>
	        		<div class="m-video-thumb"><?php echo $this->getMobileEmbed($_video, 78, 56, false); ?></div>
	        	<?php else: ?>
				<a class="video-thumb" modal="width=650;height=400" rel="iblightbox" href="<?php echo $this->getVideoGalleryUrl( $_video ); ?>" target="_blank" title="<?php echo $this->htmlEscape($_video['label']) ?> " style="width:78px; height:56px">
					<span></span>
					<img style="margin-top:-11px" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_video['file'])->resize(78,78); ?>" width="78" height="78" alt="<?php echo $this->htmlEscape($_video['label']) ?>"  title="<?php echo $_video['label'] . ($_video['label'] && $_video['description']? ' - ' : '')  .$this->htmlEscape($_video['description']) ?>"/>
				</a>
				<?php endif; ?>
	        </li>
	    <?php endforeach; ?>
	    </ul>
	    <?php endif;?>
	</div>
	<?php endif; ?>

</div>


<script type="text/javascript">
Varien.Tabs = Class.create();
Varien.Tabs.prototype = {
  initialize: function(selector) {
    var self=this;
    $$(selector+' a').each(this.initTab.bind(this));
  },

  initTab: function(el) {
      el.href = 'javascript:void(0)';
      if ($(el.parentNode).hasClassName('active')) {
        this.showContent(el);
      }
      el.observe('click', this.showContent.bind(this, el));
  },

  showContent: function(a) {
    var li = $(a.parentNode), ul = $(li.parentNode);
    ul.getElementsBySelector('li', 'ol').each(function(el){
      var contents = $(el.id+'-contents');
      if (el==li) {
        el.addClassName('active');
        contents.show();
      } else {
        el.removeClassName('active');
        contents.hide();
      }
    });
    
    return false;
  }
}

var sections = $$('.product-img-box .more-views');
var haveVideos = <?php echo count($this->getVideoGallery()) > 0 ? 'true' : 'false'; ?>;
var haveImages = haveVideos ? sections.length==2 : sections.length==1;
var pointer = $$('.zoom').first() ? $$('.zoom').first() : ($('track_outer') ? $('track_outer') : $$('.product-img-box .product-image').first());

if (pointer)
{
	if (haveImages && haveVideos)
	{
		// Both tabs
		Element.insert(pointer, {'after':'        \
		<ul class="media-tabs">                                                         \
			<li id="media-tab-images" class="first active"><a href="#">Images</a></li>  \
			<li id="media-tab-videos" class="last"><a href="#"><?php echo $this->__('Videos')?></a></li>          \
		</ul> <div style="clear:both"></div>'});
		
		sections[0].id="media-tab-images-contents";
		sections[1].id="media-tab-videos-contents";
	}
	else if (haveImages && !haveVideos)
	{
		// Only Images Tab
		Element.insert(pointer, {'after':'        \
		<ul class="media-tabs">                                                         \
			<li id="media-tab-images" class="first active"><a href="#"><?php echo $this->__('Images')?></a></li>  \
		</ul> <div style="clear:both"></div>'});
		
		sections[0].id="media-tab-images-contents";
	}
	else if (haveVideos && !haveImages)
	{
		// Only Videos Tab
		Element.insert(pointer, {'after':'        \
		<ul class="media-tabs">                                                         \
			<li id="media-tab-videos" class="first active"><a href="#"><?php echo $this->__('Videos')?></a></li>          \
		</ul> <div style="clear:both"></div>'});
		
		sections[0].id="media-tab-videos-contents";
	}
	
	new Varien.Tabs('.media-tabs');
}
</script>  

