<div class="product-image-popup">
    <p class="a-right"><a href="#" onclick="window.close(); return false;"><?php echo $this->__('Close Window') ?></a></p>
    <div id="videoContainer">
    	<?php echo $this->getVideoObjectBlock( $this->getCurrentImage() ); ?>
    </div>
    <p class="a-right"><a href="#" onclick="window.close(); return false;"><?php echo $this->__('Close Window') ?></a></p>
</div>

