<?php
/**
 * This is a modified version of the core catalog/product/view/media.phtml
 * Any changes you had made to the previous media file must be changed here as well for changes to take effect.
 * System > Configuration > Video Gallery > Display Style > Style 01
 */
?>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('videogallery');
?>
<div id="vg-style-01">
	<?php if (count($this->getVideoGallery()) > 0): ?>
	<h3>Video</h3>

	<?php
		$_collection = $this->getVideoGallery();
		$_video = $_collection[0];
		$_model = Mage::helper('videogallery/video')->getVideoByValue( $_video['value'] , $_video['provider']);

		echo $_model->getEmbedCode($_helper->getDefaultVideoWidth(), $_helper->getDefaultVideoHeight());
	?>
	
	<?php endif; ?>

	<script>
	</script>
</div>
