<?php
/**
 * This is a modified version of the core catalog/product/view/media.phtml
 * Any changes you had made to the previous media file must be changed here as well for changes to take effect.
 * System > Configuration > Video Gallery > Display Style > Style 01
 */
?>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('videogallery');
?>
<div id="vg-style-01">
	<?php if (count($this->getVideoGallery()) > 0): ?>
	<h3>Video</h3>

	<?php
		$_collection = $this->getVideoGallery();
		$_video = $_collection[0];
		$_model = Mage::helper('videogallery/video')->getVideoByValue( $_video['value'] , $_video['provider']);

		echo $_model->getEmbedCode('1024', '612');
	?>
	
	<?php endif; ?>

	<script>
		function fix_video_object(){
			var object = jQuery('#vg-style-01 .video-object');
			object.width('100%');

			var height = object.width() * 612 / 1024;
			object.height(height);
		}

		jQuery( window ).resize(function() {
		  fix_video_object();
		});
		
		fix_video_object();
		
		

		jQuery('#ytplayer').attr('width', '100%').attr('height', '100%');
	</script>
</div>
