<?php
/**
 * This is a modified version of the core catalog/product/view/media.phtml
 * Any changes you had made to the previous media file must be changed here as well for changes to take effect.
 * System > Configuration > Video Gallery > Display Style > Style 01
 */
?>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<div id="vg-style-01">
<?php echo $this->getImagesMedia(); ?>
	<?php if (count($this->getVideoGallery()) > 0): ?>
	<div class="other-views" style="margin-left:5px;font-size:10px">VIDEOS</div>
	<div class="more-views move-video-views">
		<?php if (count($this->getVideoGallery()) > 0): ?>
		<?php $isMobile = $this->isMobile(); ?>
	    <ul class="video-gallery-links">
	    <?php foreach ($this->getVideoGallery() as $_video): ?>
	        <li>
	        	<?php if ($isMobile): ?>
	        		<div class="m-video-thumb"><?php echo $this->getMobileEmbed($_video, 78, 56, false); ?></div>
	        	<?php else: ?>
				<a class="video-thumb" modal="width=650;height=400" rel="iblightbox" href="<?php echo $this->getVideoGalleryUrl( $_video ); ?>" target="_blank" title="<?php echo $this->htmlEscape($_video['label']) ?> " style="width:78px; height:56px">
					<span></span>
					<img style="margin-top:-11px" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_video['file'])->resize(78,78); ?>" width="78" height="78" alt="<?php echo $this->htmlEscape($_video['label']) ?>"  title="<?php echo $_video['label'] . ($_video['label'] && $_video['description']? ' - ' : '')  .$this->htmlEscape($_video['description']) ?>"/>
				</a>
				<?php endif; ?>
	        </li>
	    <?php endforeach; ?>
	    </ul>
	    <?php endif;?>
	</div>
	<?php endif; ?>
</div>

<?php
	$_collection = $this->getVideoGallery();
	$_video = $_collection[0];
	$_model = Mage::helper('videogallery/video')->getVideoByValue( $_video['value'] , $_video['provider']);
?>

<script>
	jQuery('.video-gallery-links a').on('click', function(e){
		e.preventDefault();
		jQuery.get(jQuery(this).attr('href'), function(html){

			jQuery('.product-image .video-object').remove();
			jQuery('.product-image').append(html);
			jQuery('.product-image img').hide();
		});
	});

	jQuery('.media-gallery-links li').on('click', function(e){
		jQuery('.product-image img').show();
		jQuery('.product-image .video-object').remove();
	});


</script>