<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Finder
 */
?>
<?php $finderId = 'amfinder_' . uniqid(); ?>
<form method="post" action="<?php echo $this->getActionUrl() ?>">
	<input type="hidden" name="finder_id" value="<?php echo $this->getId() ?>"/>
	<input type="hidden" name="back_url" value="<?php echo $this->getBackUrl() ?>"/>
	<input type="hidden" name="category_id" value="<?php echo $this->getCurrentCategoryId() ?>"/>
	<div class="amfinder-horizontal" id="<?php echo $finderId ?>Container">
	<table>
	<tr>
        <td>
            <strong>Choose your car</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </td>
    	<?php foreach ($this->getFinder()->getDropdowns() as $dropdown): ?>
    	<td>
    		<div class="dropdown-title"><?php echo $this->htmlEscape($dropdown->getName()) ?></div>
    		<div class="dropdown-element">
    			<select class="chosen-select" data-placeholder="<?php echo $this->htmlEscape($dropdown->getName()) ?>" data-no_results_text="" disable-search="true" <?php echo $this->getDropdownAttributes($dropdown)?>>
					<?php foreach($this->getDropdownValues($dropdown) as $v): ?>
						<option value="<?php echo $v['value'] ?>" <?php if ($v['selected']):?>selected="selected"<?php endif ?>>
						    <?php echo $this->htmlEscape($v['label']) ?>
						</option>
					<?php endforeach ?>
    			</select> &nbsp;
    		</div>
    	</td>
    	<?php endforeach ?>
    	<td>
        	<div class="amfinder-buttons">
        		<button class="button btn btn-white" title="<?php echo $this->__('GO') ?>" type="submit"><?php echo $this->__('Find') ?></button>
            </div>
    	</td>
	</tr>
	</table>
	</div>
</form>
<script type="text/javascript">
var <?php echo $finderId ?>  = new amFinder(
    '<?php echo $finderId ?>Container', 
    '<?php echo $this->getAjaxUrl() ?>', 
    '<?php echo $this->__('Loading...')?>',
    '<?php echo Mage::getStoreConfig('amfinder/general/partial_search')?>',
    <?php echo intval(Mage::getStoreConfig('amfinder/general/auto_submit')) ?>
);
</script>